import dynamic from "next/dynamic";
import React from "react";

/**
 * Registry of available storefront templates.
 *
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated by scripts/sync-template-registry.ts
 *
 * To add a new template:
 * 1. Upload via the template upload API, OR
 * 2. Add template files to /templates/{slug}/ directory
 * 3. Run: npm run sync-templates
 *
 * Last generated: 2026-02-06T11:00:00.000Z
 */

export const TEMPLATE_COMPONENTS: Record<string, any> = {
  "gta-cannabis": dynamic(() => import("@/templates/gta-cannabis/index")),
  "healingbuds": dynamic(() => import("@/templates/healingbuds/index")),
  "wellness-nature": dynamic(() => import("@/templates/wellness-nature/index")),
};

/**
 * Registry of template-specific Navigation components.
 * Templates without a specific navigation will use the default platform navigation.
 */
export const TEMPLATE_NAVIGATION: Record<string, any> = {
  "gta-cannabis": dynamic(() => import("@/templates/gta-cannabis/components/Navigation").then((m: any) => m.default || m)),
  "healingbuds": dynamic(() => import("@/templates/healingbuds/components/Navigation").then((m: any) => m.default || m)),
  "wellness-nature": dynamic(() => import("@/templates/wellness-nature/components/Navigation").then((m: any) => m.default || m)),
};

/**
 * Registry of template-specific Footer components.
 * Templates without a specific footer will use the default platform footer.
 */
export const TEMPLATE_FOOTER: Record<string, any> = {
  "gta-cannabis": dynamic(() => import("@/templates/gta-cannabis/components/Footer").then((m: any) => m.default || m)),
  "healingbuds": dynamic(() => import("@/templates/healingbuds/components/Footer").then((m: any) => m.default || m)),
  "wellness-nature": dynamic(() => import("@/templates/wellness-nature/components/Footer").then((m: any) => m.default || m)),
};
