import dynamic from "next/dynamic";
import React from "react";

/**
 * Registry of available storefront templates.
 *
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated by scripts/sync-template-registry.ts
 *
 * To add a new template:
 * 1. Upload via the template upload API, OR
 * 2. Add template files to /templates/{slug}/ directory
 * 3. Run: npm run sync-templates
 *
 * NOTE: gta-cannabis and wellness-nature have been migrated to data-only
 * format (layout.json in S3). They no longer need React component entries here.
 *
 * Last generated: 2026-02-11T14:15:00.000Z
 */

export const TEMPLATE_COMPONENTS: Record<string, any> = {
  "healingbuds": dynamic(() => import("@/templates/healingbuds/index")),
};

/**
 * Registry of template-specific Navigation components.
 * Templates without a specific navigation will use the default platform navigation.
 */
export const TEMPLATE_NAVIGATION: Record<string, any> = {
  "healingbuds": dynamic(() => import("@/templates/healingbuds/components/Navigation").then((m: any) => m.default || m)),
};

/**
 * Registry of template-specific Footer components.
 * Templates without a specific footer will use the default platform footer.
 */
export const TEMPLATE_FOOTER: Record<string, any> = {
  "healingbuds": dynamic(() => import("@/templates/healingbuds/components/Footer").then((m: any) => m.default || m)),
};
