import { Metadata } from "next";
import Link from "next/link";
import { FileSignature, FileText } from "lucide-react";
import Navbar from "@/components/landing/Navbar";
import Footer from "@/components/landing/Footer";

export const metadata: Metadata = {
    title: "Data Processing Agreement | BudStacks",
    description: "GDPR Article 28 Data Processing Agreement between BudStacks and operators.",
};

const SECTIONS = [
    {
        id: "parties",
        title: "1. Parties and roles",
        body: (
            <>
                <p>
                    This Data Processing Agreement ("DPA") forms part of the Terms of Service between
                    Budstacks Lda ("BudStacks", "Processor") and the operator entity ("Operator",
                    "Controller") that has accepted it. It governs the processing of personal data
                    by BudStacks on behalf of the Operator in connection with the BudStacks platform.
                </p>
                <p>
                    Where applicable, the EU Standard Contractual Clauses (Module Two — Controller to
                    Processor, Commission Implementing Decision (EU) 2021/914) and the UK
                    International Data Transfer Addendum (B1.0) are incorporated by reference for
                    transfers outside the EEA / United Kingdom.
                </p>
            </>
        ),
    },
    {
        id: "subject",
        title: "2. Subject matter, duration, nature and purpose",
        body: (
            <>
                <ul>
                    <li>
                        <strong>Subject matter:</strong> processing of personal data by BudStacks to
                        provide the platform services described in the Terms of Service.
                    </li>
                    <li>
                        <strong>Duration:</strong> for the term of the agreement and any post-termination
                        period required for data export, return, or deletion.
                    </li>
                    <li>
                        <strong>Nature and purpose:</strong> hosting, storing, processing, and
                        transmitting personal data submitted by the Operator or generated by
                        end-customers using the Operator's storefront.
                    </li>
                    <li>
                        <strong>Categories of data subjects:</strong> Operator's employees, end-customers,
                        patients, prospects, and authorised users of the Operator's storefront.
                    </li>
                    <li>
                        <strong>Categories of personal data:</strong> identifiers (name, email, phone),
                        addresses, account credentials (hashed), order data, payment-method tokens,
                        and — where the Operator chooses to upload it — health-related data
                        (prescriptions, KYC, conditions) classified as special-category data under
                        GDPR Article 9.
                    </li>
                </ul>
            </>
        ),
    },
    {
        id: "controller-instructions",
        title: "3. Controller instructions",
        body: (
            <>
                <p>
                    BudStacks processes personal data only on the Operator's documented instructions
                    (including the Terms of Service, this DPA, and the operating settings configured
                    in the platform), unless required by Union or member-state law. BudStacks will
                    inform the Operator of any such legal requirement before processing, unless that
                    law prohibits such notification on important grounds of public interest.
                </p>
            </>
        ),
    },
    {
        id: "confidentiality",
        title: "4. Confidentiality",
        body: (
            <>
                <p>
                    BudStacks ensures that personnel authorised to process personal data are bound
                    by appropriate confidentiality obligations and trained in data protection.
                </p>
            </>
        ),
    },
    {
        id: "security",
        title: "5. Security measures (Article 32)",
        body: (
            <>
                <p>BudStacks implements appropriate technical and organisational measures including:</p>
                <ul>
                    <li>Encryption in transit (TLS 1.2 or higher) and at rest</li>
                    <li>Access control on the principle of least privilege; multi-factor authentication for administrative access</li>
                    <li>Network segmentation; isolation of tenant data partitions</li>
                    <li>Audit logging of administrative and security events</li>
                    <li>Regular dependency scanning, vulnerability management, and patching</li>
                    <li>Backups and tested restore procedures</li>
                    <li>Documented incident-response and business-continuity plans</li>
                </ul>
                <p>
                    Detailed security documentation is available to Operators on request under NDA.
                </p>
            </>
        ),
    },
    {
        id: "subprocessors",
        title: "6. Sub-processors (Article 28(2)(4))",
        body: (
            <>
                <p>
                    The Operator grants general authorisation for BudStacks to engage sub-processors,
                    subject to the following conditions:
                </p>
                <ul>
                    <li>
                        The current list is published at{" "}
                        <Link href="/legal/subprocessors" className="text-bs-green-300 underline-offset-2 hover:underline">
                            /legal/subprocessors
                        </Link>
                        .
                    </li>
                    <li>
                        BudStacks notifies the Operator by email at least 30 days before adding or
                        replacing a sub-processor.
                    </li>
                    <li>
                        The Operator may reasonably object to a new sub-processor within 14 days of
                        notice. If the parties cannot agree a resolution, the Operator may terminate
                        the affected services with a pro-rata refund of pre-paid fees.
                    </li>
                    <li>
                        BudStacks imposes data-protection obligations on each sub-processor that are
                        no less protective than those in this DPA, and remains liable for the
                        sub-processor's performance.
                    </li>
                </ul>
            </>
        ),
    },
    {
        id: "data-subject-rights",
        title: "7. Assistance with data-subject rights (Article 28(3)(e))",
        body: (
            <>
                <p>
                    BudStacks provides reasonable assistance, including via in-platform tooling,
                    APIs, and support, to help the Operator respond to requests from data subjects
                    exercising rights under Articles 15–22 GDPR (access, rectification, erasure,
                    restriction, portability, objection).
                </p>
            </>
        ),
    },
    {
        id: "breach",
        title: "8. Personal-data breach notification (Article 33)",
        body: (
            <>
                <p>
                    BudStacks notifies the Operator without undue delay and in any event within 72
                    hours of becoming aware of a personal-data breach affecting the Operator's data,
                    providing the information required by Article 33(3) GDPR to the extent then
                    available, with subsequent updates as more information becomes known.
                </p>
            </>
        ),
    },
    {
        id: "dpia",
        title: "9. Data Protection Impact Assessments (Articles 35–36)",
        body: (
            <>
                <p>
                    BudStacks provides reasonable assistance to the Operator in carrying out
                    DPIAs and, where required, prior consultations with supervisory authorities.
                </p>
            </>
        ),
    },
    {
        id: "deletion",
        title: "10. Return or deletion of data (Article 28(3)(g))",
        body: (
            <>
                <p>
                    On termination of the agreement, BudStacks will, at the Operator's choice, delete
                    or return all personal data, and delete existing copies, unless retention is
                    required by Union or member-state law. The platform provides export tooling
                    accessible for 30 days post-termination; thereafter data is deleted within 90
                    days, subject to backup retention windows.
                </p>
            </>
        ),
    },
    {
        id: "audit",
        title: "11. Audit rights (Article 28(3)(h))",
        body: (
            <>
                <p>
                    BudStacks makes available to the Operator information necessary to demonstrate
                    compliance with Article 28 GDPR, and allows for and contributes to audits,
                    including inspections, conducted by the Operator or another auditor mandated by
                    the Operator. Audits are conducted at the Operator's expense, on at least 30
                    days' written notice, no more than once per year (unless required by a
                    supervisory authority or following a confirmed breach), and subject to
                    reasonable confidentiality, security, and operational-impact constraints.
                </p>
            </>
        ),
    },
    {
        id: "transfers",
        title: "12. International transfers",
        body: (
            <>
                <p>
                    Where personal data is transferred outside the EEA / United Kingdom, the EU
                    Standard Contractual Clauses (Module Two) and the UK Addendum apply, with the
                    transfer details set out in the sub-processor list. BudStacks implements
                    additional technical and organisational measures (including encryption and
                    access controls) where required by the recipient jurisdiction's risk profile.
                </p>
            </>
        ),
    },
    {
        id: "liability",
        title: "13. Liability",
        body: (
            <>
                <p>
                    The liability of each party under this DPA is subject to the limitations and
                    exclusions of liability set out in the Terms of Service.
                </p>
            </>
        ),
    },
    {
        id: "acceptance",
        title: "14. Acceptance",
        body: (
            <>
                <p>
                    Operators accept this DPA as part of onboarding. A countersigned PDF copy is
                    available on request from{" "}
                    <a href="mailto:legal@budstacks.io" className="text-bs-green-300 underline-offset-2 hover:underline">
                        legal@budstacks.io
                    </a>
                    . The current version of the DPA is recorded in the{" "}
                    <Link href="/legal/changelog" className="text-bs-green-300 underline-offset-2 hover:underline">
                        legal changelog
                    </Link>
                    .
                </p>
            </>
        ),
    },
];

export default function DpaPage() {
    return (
        <div className="budstacks-theme min-h-screen">
            <Navbar />
            <main className="px-4 pt-32 pb-24 sm:px-6 lg:px-8">
                <div className="mx-auto max-w-4xl">
                    <div className="mb-12 text-center">
                        <div className="mb-4 flex justify-center">
                            <div className="section-badge">
                                <FileSignature className="h-4 w-4" />
                                Legal
                            </div>
                        </div>
                        <h1 className="font-bs-serif text-3xl font-medium tracking-[-0.02em] text-bs-gold-300 sm:text-4xl md:text-5xl">
                            Data Processing Agreement
                        </h1>
                        <p className="mx-auto mt-4 max-w-2xl text-lg text-bs-fg-2">
                            Last updated: April 25, 2026 · Version 1 (draft)
                        </p>
                    </div>


                    <div className="card-floating p-10 lg:p-12">
                        <div className="bs-article max-w-none">
                            {SECTIONS.map((s) => (
                                <section key={s.id} id={s.id} className="mb-10 last:mb-0">
                                    <h2 className="font-bs-serif text-2xl font-medium text-bs-fg-0 mb-4">
                                        {s.title}
                                    </h2>
                                    <div className="leading-relaxed text-bs-fg-2 [&_ul]:my-3 [&_ul]:list-disc [&_ul]:pl-6 [&_li]:mb-1.5 [&_p]:mb-3">
                                        {s.body}
                                    </div>
                                </section>
                            ))}
                        </div>
                    </div>

                    <div className="mt-8 flex flex-wrap justify-center gap-4">
                        <Link href="/terms" className="text-sm text-bs-fg-2 hover:text-bs-green-300 flex items-center gap-2">
                            <FileText className="h-4 w-4" />
                            Terms of Service
                        </Link>
                        <Link href="/privacy" className="text-sm text-bs-fg-2 hover:text-bs-green-300 flex items-center gap-2">
                            <FileText className="h-4 w-4" />
                            Privacy Policy
                        </Link>
                        <Link href="/legal/subprocessors" className="text-sm text-bs-fg-2 hover:text-bs-green-300 flex items-center gap-2">
                            <FileText className="h-4 w-4" />
                            Sub-processors
                        </Link>
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    );
}
