/**
 * Template Registry Sync Script
 * Automatically syncs the template registry with templates in the filesystem
 *
 * This script:
 * 1. Scans the templates directory
 * 2. Generates dynamic import statements for each template
 * 3. Updates lib/template-registry.ts automatically
 *
 * Run this after uploading a new template to make it available without manual registry updates
 */

import { promises as fs } from 'fs';
import path from 'path';

const TEMPLATES_DIR = path.join(process.cwd(), 'templates');
const REGISTRY_FILE = path.join(process.cwd(), 'lib', 'template-registry.ts');

interface TemplateInfo {
  slug: string;
  hasNavigation: boolean;
  hasFooter: boolean;
}

async function scanTemplates(): Promise<TemplateInfo[]> {
  const templates: TemplateInfo[] = [];

  try {
    const entries = await fs.readdir(TEMPLATES_DIR, { withFileTypes: true });

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;

      const slug = entry.name;
      const templatePath = path.join(TEMPLATES_DIR, slug);

      // Check for required index file
      const indexPath = path.join(templatePath, 'index.tsx');
      try {
        await fs.access(indexPath);
      } catch {
        console.warn(`⚠️  Template ${slug} missing index.tsx, skipping`);
        continue;
      }

      // Check for optional Navigation and Footer components
      const componentsPath = path.join(templatePath, 'components');
      let hasNavigation = false;
      let hasFooter = false;

      try {
        await fs.access(path.join(componentsPath, 'Navigation.tsx'));
        hasNavigation = true;
      } catch {}

      try {
        await fs.access(path.join(componentsPath, 'Footer.tsx'));
        hasFooter = true;
      } catch {}

      templates.push({ slug, hasNavigation, hasFooter });
    }
  } catch (error) {
    console.error('❌ Error scanning templates directory:', error);
    throw error;
  }

  return templates;
}

function generateRegistryContent(templates: TemplateInfo[]): string {
  const componentImports = templates
    .map(t => `  "${t.slug}": dynamic(() => import("@/templates/${t.slug}/index")),`)
    .join('\n');

  const navigationImports = templates
    .filter(t => t.hasNavigation)
    .map(t => `  "${t.slug}": dynamic(() => import("@/templates/${t.slug}/components/Navigation").then((m: any) => m.default || m)),`)
    .join('\n');

  const footerImports = templates
    .filter(t => t.hasFooter)
    .map(t => `  "${t.slug}": dynamic(() => import("@/templates/${t.slug}/components/Footer").then((m: any) => m.default || m)),`)
    .join('\n');

  return `import dynamic from "next/dynamic";
import React from "react";

/**
 * Registry of available storefront templates.
 *
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated by scripts/sync-template-registry.ts
 *
 * To add a new template:
 * 1. Upload via the template upload API, OR
 * 2. Add template files to /templates/{slug}/ directory
 * 3. Run: npm run sync-templates
 *
 * Last generated: ${new Date().toISOString()}
 */

export const TEMPLATE_COMPONENTS: Record<string, any> = {
${componentImports}
};

/**
 * Registry of template-specific Navigation components.
 * Templates without a specific navigation will use the default platform navigation.
 */
export const TEMPLATE_NAVIGATION: Record<string, any> = {
${navigationImports}
};

/**
 * Registry of template-specific Footer components.
 * Templates without a specific footer will use the default platform footer.
 */
export const TEMPLATE_FOOTER: Record<string, any> = {
${footerImports}
};
`;
}

async function syncRegistry() {
  console.log('🔄 Syncing template registry...\n');

  // Scan templates
  console.log(`📂 Scanning templates directory: ${TEMPLATES_DIR}`);
  const templates = await scanTemplates();

  console.log(`\n✅ Found ${templates.length} template(s):`);
  templates.forEach(t => {
    const extras = [];
    if (t.hasNavigation) extras.push('Navigation');
    if (t.hasFooter) extras.push('Footer');
    const extrasStr = extras.length > 0 ? ` (+ ${extras.join(', ')})` : '';
    console.log(`   - ${t.slug}${extrasStr}`);
  });

  // Generate new registry content
  console.log('\n📝 Generating registry file...');
  const registryContent = generateRegistryContent(templates);

  // Write to file
  await fs.writeFile(REGISTRY_FILE, registryContent, 'utf-8');
  console.log(`✅ Registry updated: ${REGISTRY_FILE}`);

  console.log('\n🎉 Template registry sync complete!');
  console.log('\n💡 Next steps:');
  console.log('   1. Review the updated registry file');
  console.log('   2. Commit the changes to git');
  console.log('   3. Deploy to production for templates to go live');
}

// Run the sync
syncRegistry().catch(error => {
  console.error('\n❌ Registry sync failed:', error);
  process.exit(1);
});
