/**
 * SEO Supercharge US-020 — the redirect table's rules, with no I/O in any of
 * them.
 *
 * Three callers share this module and they MUST agree, or a redirect an owner
 * saved is a redirect that never fires:
 *   - the write route (`app/api/tenant-admin/seo/redirects/*`), which stores the
 *     normalised form;
 *   - the read feed (`app/api/public/seo/redirects`), which hands the table to
 *     middleware;
 *   - middleware itself, which normalises the INCOMING pathname with the same
 *     function before comparing.
 *
 * PURE, and deliberately so: middleware runs in the edge runtime, where Prisma,
 * `next/headers` and Node built-ins are all unavailable. Nothing here may import
 * anything that reaches them.
 *
 * CASE. `fromPath` is stored lower-cased and matched lower-cased, which is what
 * makes `@@unique([tenantId, fromPath])` a real duplicate guard rather than a
 * near-miss one — without it `/Sale` and `/sale` are two rows that both claim
 * the same request and the winner is whatever the query planner felt like.
 * Storefront URLs are lower-case throughout (slugs, condition keys, static
 * pages), so nothing legitimate is lost. `toPath` keeps its case: it is a
 * destination, not a key, and the browser is going to be shown it.
 */

/** The only two status codes an owner may pick. Both are permanent. */
export const SEO_REDIRECT_STATUS_CODES = [301, 308] as const;
export type SeoRedirectStatusCode = (typeof SEO_REDIRECT_STATUS_CODES)[number];

/**
 * 301 by default: it is the code every SEO tool, every crawler and every piece
 * of advice on the subject means by "redirect". 308 exists for the owner who
 * needs the method preserved and knows why.
 */
export const SEO_REDIRECT_DEFAULT_STATUS: SeoRedirectStatusCode = 301;

/**
 * A hard cap per tenant, enforced at WRITE time rather than read time.
 *
 * Middleware caches the whole table per tenant and matches against it in
 * memory, so the table has to be complete — a read-side `take` would silently
 * drop the 501st redirect and leave an owner staring at a rule that exists in
 * the UI and does nothing on the site. Refusing the write is the honest failure.
 */
export const SEO_REDIRECT_MAX_PER_TENANT = 500;

/** Long enough for any real URL; short enough that the table stays small. */
export const SEO_REDIRECT_MAX_PATH_LENGTH = 512;

/**
 * How far a chain may be followed before it is called a loop. A legitimate
 * chain is one or two hops (a page moved twice); ten is already pathological.
 */
const MAX_CHAIN_HOPS = 10;

export interface SeoRedirectRule {
  /** Normalised AND lower-cased — the match key. */
  readonly fromPath: string;
  /** Normalised, case preserved. */
  readonly toPath: string;
  readonly statusCode: number;
}

/**
 * Path prefixes an owner may never claim.
 *
 * `/api`, `/tenant-admin` and `/super-admin` are the platform's own surfaces —
 * a redirect on any of them is at best a broken admin panel and at worst a
 * tenant pointing another tenant's API call somewhere else. `/_next` and
 * `/__clerk` are framework plumbing: middleware already carves them out, so a
 * rule there would be dead weight that looks like it works.
 */
const RESERVED_PREFIXES = [
  "/api",
  "/tenant-admin",
  "/super-admin",
  "/_next",
  "/__clerk",
] as const;

/**
 * Exact paths an owner may never claim. Both are generated by the app itself
 * (app/store/[slug]/robots.txt, .../sitemap.xml) and both are how a crawler
 * finds everything else — redirecting either is how a store disappears.
 */
const RESERVED_EXACT = ["/sitemap.xml", "/robots.txt"] as const;

/**
 * Normalise a path to the one form everything else compares against, or null
 * when the input is not a path this feature will touch.
 *
 * Rejected outright rather than coerced:
 *   - anything with a scheme (`https:`, `javascript:`, `mailto:`) — an external
 *     destination is an OPEN REDIRECT the moment it is not validated, and
 *     validating one is a different story than this one;
 *   - whitespace and control characters, which have no business in a stored
 *     path and are how a header-injection attempt looks;
 *   - `..` segments, which mean nothing here and everything to a naive joiner.
 *
 * Coerced rather than rejected:
 *   - a missing leading slash (`products` → `/products`);
 *   - repeated slashes (`//evil.com` → `/evil.com`) — THIS ONE IS SECURITY, not
 *     tidiness: `//evil.com` is a protocol-relative URL, and a redirect to it
 *     leaves the store;
 *   - a query string or fragment, dropped: the table matches on path alone, and
 *     the incoming query is carried across to the destination by middleware;
 *   - a trailing slash, dropped, so `/sale/` and `/sale` are one rule.
 */
export function normalizeRedirectPath(raw: unknown): string | null {
  if (typeof raw !== "string") return null;

  const trimmed = raw.trim();
  if (!trimmed || trimmed.length > SEO_REDIRECT_MAX_PATH_LENGTH) return null;
  if (/^[a-z][a-z0-9+.-]*:/i.test(trimmed)) return null;
  // eslint-disable-next-line no-control-regex
  if (/[\s]|[\u0000-\u001f\u007f]/.test(trimmed)) return null;

  const withoutQuery = trimmed.split(/[?#]/)[0];
  if (!withoutQuery) return null;

  const collapsed = `/${withoutQuery}`.replace(/\/{2,}/g, "/");
  if (collapsed.split("/").includes("..")) return null;

  const trimmedTrailing =
    collapsed.length > 1 ? collapsed.replace(/\/+$/, "") : collapsed;
  return trimmedTrailing || "/";
}

/**
 * The lower-cased normalised form — the key `fromPath` is stored under and the
 * key an incoming pathname is looked up by. See the module docstring for why
 * case is folded on this side and preserved on the destination.
 */
export function redirectMatchKey(raw: unknown): string | null {
  return normalizeRedirectPath(raw)?.toLowerCase() ?? null;
}

/** Is this a path the platform owns? Expects an already-normalised path. */
export function isReservedRedirectPath(path: string): boolean {
  const lower = path.toLowerCase();
  if (RESERVED_EXACT.includes(lower as (typeof RESERVED_EXACT)[number])) {
    return true;
  }
  return RESERVED_PREFIXES.some(
    (prefix) => lower === prefix || lower.startsWith(`${prefix}/`),
  );
}

/** Narrow an arbitrary value to one of the two permitted status codes. */
export function parseRedirectStatusCode(
  value: unknown,
): SeoRedirectStatusCode | null {
  const numeric = typeof value === "string" ? Number(value) : value;
  return SEO_REDIRECT_STATUS_CODES.includes(
    numeric as SeoRedirectStatusCode,
  )
    ? (numeric as SeoRedirectStatusCode)
    : null;
}

export type RedirectChainProblem = "self_redirect" | "loop";

/**
 * Would saving `candidate` create a rule that redirects to itself, directly or
 * around a chain?
 *
 * Refused AT WRITE TIME because there is no good place to refuse it later:
 * middleware follows exactly one hop (see `resolveStoreRedirect`), so a loop
 * does not hang a request — it produces a redirect to a URL that immediately
 * redirects back, and the BROWSER is what gives up, with
 * ERR_TOO_MANY_REDIRECTS on the owner's own storefront. A crawler drops the
 * page entirely, which is the precise opposite of what a redirect manager is
 * bought for.
 *
 * A rule already stored under the candidate's `fromPath` is excluded from the
 * chain: an edit REPLACES it, so validating against the row being overwritten
 * would refuse every legitimate change to it.
 */
export function findRedirectChainProblem(
  existing: readonly SeoRedirectRule[],
  candidate: { fromPath: string; toPath: string },
): RedirectChainProblem | null {
  const from = redirectMatchKey(candidate.fromPath);
  const to = redirectMatchKey(candidate.toPath);
  if (!from || !to) return null;
  if (from === to) return "self_redirect";

  const chain = new Map<string, string>();
  for (const rule of existing) {
    const ruleFrom = redirectMatchKey(rule.fromPath);
    const ruleTo = redirectMatchKey(rule.toPath);
    if (!ruleFrom || !ruleTo || ruleFrom === from) continue;
    chain.set(ruleFrom, ruleTo);
  }
  chain.set(from, to);

  const seen = new Set<string>([from]);
  let current = to;
  for (let hop = 0; hop < MAX_CHAIN_HOPS; hop += 1) {
    if (seen.has(current)) return "loop";
    seen.add(current);
    const next = chain.get(current);
    if (!next) return null;
    current = next;
  }
  return "loop";
}

/**
 * The rule that claims `pathname`, or null.
 *
 * EXACT match only. Prefix and wildcard matching are not here on purpose: a
 * prefix rule silently swallows every page beneath it, which is a store-wide
 * outage authored in one text box, and nothing in the PRD asks for it.
 *
 * A linear scan rather than a Map because the caller is middleware holding a
 * capped array (≤ `SEO_REDIRECT_MAX_PER_TENANT`) of already-normalised keys —
 * a few hundred string comparisons, against building a Map per request.
 */
export function matchRedirect(
  rules: readonly SeoRedirectRule[],
  pathname: string,
): SeoRedirectRule | null {
  const key = redirectMatchKey(pathname);
  if (!key) return null;
  for (const rule of rules) {
    if (rule.fromPath === key) return rule;
  }
  return null;
}
