-- AlterEnum: Add PENDING_SYNC to OrderStatus
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PENDING_SYNC';

-- AlterEnum: Add AWAITING_PROCESSING to PaymentStatus
ALTER TYPE "PaymentStatus" ADD VALUE IF NOT EXISTS 'AWAITING_PROCESSING';
