/**
 * US-022 — a published Wire post, expressed as a campaign draft.
 *
 * The Wire's editor (`components/editor/tiptap.tsx`) and the email composer
 * (US-012) are deliberately different editors with different schemas: one
 * targets a web page, the other an inbox. So a post cannot simply be handed to
 * the campaign save path as HTML — it is REPARSED against the email schema by
 * `generateJSON`, and anything the email schema has no node for is dropped by
 * ProseMirror's parser on the way in. That loss is the feature. A post's iframe
 * embed or its `<video>` has no meaning in an inbox and would be stripped by
 * `lib/security/email-sanitize.ts` at the far end regardless; dropping it here
 * means the author reviews the actual email in the composer before it goes.
 *
 * IMAGES ARE LEFT AS THEY ARE STORED. The cover image and any image inside the
 * post body keep their stored `src`, and `normaliseEmailContentJson` resolves
 * each one to an absolute, durable URL when the pipeline runs (US-005/US-011) —
 * exactly the rule a composer-authored document obeys. Resolving them here as
 * well would be a second copy of that rule, free to drift.
 *
 * NOTHING HERE SENDS. This builds a document; the route stores it as a DRAFT and
 * the author opens it in the composer. There is no path from this module to the
 * queue.
 *
 * SERVER ONLY — `@tiptap/html/server` pulls in happy-dom to parse the post HTML.
 */

import { generateJSON } from "@tiptap/html/server";

import { ApiError } from "@/lib/api-error";
import { CAMPAIGN_NAME_MAX, CAMPAIGN_SUBJECT_MAX } from "@/lib/email/campaign-fields";
import { emailEditorExtensions } from "@/lib/email/editor-extensions";
import { EMAIL_BUTTON_NAME } from "@/lib/email/email-button-node";
import {
  emailContentJsonSchema,
  type EmailContentJson,
  type EmailDocNode,
} from "@/lib/email/email-content-json";
import { EMAIL_IMAGE_NAME } from "@/lib/email/email-image-node";
import { EMAIL_CONTENT_WIDTH_PX } from "@/lib/email/email-layout";

/** The storefront route a post is published at (`app/store/[slug]/the-wire/[postSlug]`). */
export const POST_STOREFRONT_PATH_PREFIX = "/the-wire/";

/** Label on the call to action that takes a reader from the inbox to the post. */
export const POST_NEWSLETTER_READ_MORE_LABEL = "Read more";

export const POST_CONTENT_UNREADABLE_MESSAGE =
  "This article's content could not be turned into an email. Open the article, re-save it, and try again.";

/** The post columns a newsletter is built from. */
export interface NewsletterSourcePost {
  readonly title: string;
  readonly slug: string;
  /** The Wire's stored HTML — reparsed, never passed through as HTML. */
  readonly content: string;
  readonly excerpt?: string | null;
  readonly coverImage?: string | null;
}

/** What the route writes to `campaigns` — a draft, never a send. */
export interface PostNewsletterDraft {
  readonly name: string;
  readonly subject: string;
  readonly contentJson: EmailContentJson;
}

/**
 * The absolute URL of a published post.
 *
 * Built from the tenant's own base URL (`getTenantBaseUrl`), the same host
 * US-003's confirm links and US-004's unsubscribe links use: an inbox has no
 * origin, so the storefront path on its own would resolve to nothing. The slug
 * is percent-encoded — it is generated by `slugify` today and so encodes to
 * itself, but this URL leaves for a recipient and the encoding is what keeps
 * that true if the slug rules ever loosen.
 */
export function postStorefrontUrl(slug: string, baseUrl: string): string {
  return `${baseUrl}${POST_STOREFRONT_PATH_PREFIX}${encodeURIComponent(slug)}`;
}

/** Trim, then cut to the column's ceiling. Never produces a partial code unit. */
function clamped(value: string, max: number): string {
  return [...value.trim()].slice(0, max).join("");
}

/**
 * The post body, reparsed against the EMAIL schema.
 *
 * The result is validated rather than cast: `generateJSON` is typed
 * `Record<string, any>`, and letting that flow into `contentJson` unchecked
 * would put the one value this whole pipeline is built around beyond the
 * compiler's reach. A failure is the author's to act on (a 400 naming the
 * article), not a 500.
 */
function postBodyNodes(html: string): EmailDocNode[] {
  let generated: unknown;
  try {
    generated = generateJSON(html, emailEditorExtensions());
  } catch {
    throw new ApiError(POST_CONTENT_UNREADABLE_MESSAGE, 400);
  }

  const parsed = emailContentJsonSchema.safeParse(generated);
  if (!parsed.success) throw new ApiError(POST_CONTENT_UNREADABLE_MESSAGE, 400);
  return parsed.data.content ?? [];
}

/**
 * The cover image, at the top, sized to the column.
 *
 * `width` is set explicitly because Outlook renders through Word, which ignores
 * the `max-width` the body stylesheet inlines and would otherwise draw a 4000px
 * photo at its intrinsic size (see `lib/email/email-image-node.ts`). The post
 * title becomes the alt text: a cover image is decorative for the article but
 * carries the article's subject in a client that blocks images by default.
 */
function coverImageNodes(
  coverImage: string | null | undefined,
  alt: string,
): EmailDocNode[] {
  const src = coverImage?.trim();
  if (!src) return [];
  return [
    {
      type: EMAIL_IMAGE_NAME,
      attrs: { src, alt, width: EMAIL_CONTENT_WIDTH_PX },
    },
  ];
}

/**
 * The excerpt, as a standfirst above the article.
 *
 * Italic rather than a blockquote: `<em>` is on the sanitizer's allow-list and
 * needs no styling to survive, where a blockquote's left border is the kind of
 * decoration email clients disagree about.
 */
function excerptNodes(excerpt: string | null | undefined): EmailDocNode[] {
  const text = excerpt?.trim();
  if (!text) return [];
  return [
    {
      type: "paragraph",
      content: [{ type: "text", text, marks: [{ type: "italic" }] }],
    },
  ];
}

/**
 * The call to action, centred.
 *
 * A newsletter carries the article so it can be read in the inbox, but the post
 * lives on the storefront — this is the one link that has to be there, so it is
 * appended unconditionally rather than left for the author to remember.
 */
function readMoreNode(href: string): EmailDocNode {
  return {
    type: EMAIL_BUTTON_NAME,
    attrs: {
      href,
      label: POST_NEWSLETTER_READ_MORE_LABEL,
      textAlign: "center",
    },
  };
}

/**
 * Build the draft a "Send as newsletter" click creates.
 *
 * Pure: no database, no network. The caller supplies the tenant's base URL and
 * persists the result through the ordinary campaign save path, so the document
 * this returns is checked by exactly the rules a hand-authored one is —
 * including the unsubscribe assertion in `campaign-content.ts`.
 */
export function buildPostNewsletterDraft(
  post: NewsletterSourcePost,
  baseUrl: string,
): PostNewsletterDraft {
  const title = post.title.trim();

  return {
    name: clamped(title, CAMPAIGN_NAME_MAX),
    subject: clamped(title, CAMPAIGN_SUBJECT_MAX),
    contentJson: {
      type: "doc",
      content: [
        ...coverImageNodes(post.coverImage, title),
        ...excerptNodes(post.excerpt),
        ...postBodyNodes(post.content),
        readMoreNode(postStorefrontUrl(post.slug, baseUrl)),
      ],
    },
  };
}
