-- Campaign state + per-recipient delivery tracking (Email Phase 2, US-016).
--
-- A campaign is authored exactly like a template — `contentJson` is the
-- composer document, `contentHtml` is what the US-011 render pipeline derived
-- from it — so the worker's existing Handlebars compile step consumes it
-- unchanged.
--
-- `audience` stores the RULE (which lists to mail), never a resolved address
-- list: recipients are materialised into campaign_recipients at send time
-- (US-019), so the list reflects consent and suppression as they stand at send,
-- not as they stood at draft. `stats` is a denormalised progress cache for the
-- list view; the recipient rows stay the source of truth.
--
-- campaign_recipients is the per-recipient delivery record — one row per
-- address, one message per row, never a multi-address To:. `userId` and
-- `emailLogId` are plain columns with no FK on purpose: the record must survive
-- an erased customer or a pruned log row, and `users` is load-bearing (PRD-208)
-- so it gains no back-relation. The unique (campaignId, email) is what makes
-- re-materialising a send idempotent — nobody gets two copies.
--
-- Object names below were generated by `prisma migrate diff` against the schema
-- so a future diff stays clean.
--
-- See tasks/prd-email-authoring-campaigns.md (US-016..US-021, US-026).

CREATE TYPE "CampaignStatus" AS ENUM ('DRAFT', 'SCHEDULED', 'SENDING', 'SENT', 'CANCELLED');
CREATE TYPE "CampaignRecipientStatus" AS ENUM ('PENDING', 'QUEUED', 'SENT', 'FAILED', 'SUPPRESSED');

CREATE TABLE "campaigns" (
    "id"          TEXT NOT NULL,
    "tenantId"    TEXT NOT NULL,
    "name"        TEXT NOT NULL,
    "subject"     TEXT NOT NULL,
    "contentHtml" TEXT NOT NULL,
    "contentJson" JSONB,
    "status"      "CampaignStatus" NOT NULL DEFAULT 'DRAFT',
    "audience"    JSONB,
    "scheduledAt" TIMESTAMP(3),
    "sentAt"      TIMESTAMP(3),
    "stats"       JSONB,
    "createdAt"   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"   TIMESTAMP(3) NOT NULL,

    CONSTRAINT "campaigns_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "campaign_recipients" (
    "id"         TEXT NOT NULL,
    "campaignId" TEXT NOT NULL,
    "email"      TEXT NOT NULL,
    "userId"     TEXT,
    "status"     "CampaignRecipientStatus" NOT NULL DEFAULT 'PENDING',
    "emailLogId" TEXT,
    "error"      TEXT,
    "createdAt"  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"  TIMESTAMP(3) NOT NULL,

    CONSTRAINT "campaign_recipients_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "campaigns_tenantId_status_idx"
    ON "campaigns"("tenantId", "status");
CREATE INDEX "campaigns_tenantId_createdAt_idx"
    ON "campaigns"("tenantId", "createdAt");

-- Idempotent fan-out: one row per address per campaign.
CREATE UNIQUE INDEX "campaign_recipients_campaignId_email_key"
    ON "campaign_recipients"("campaignId", "email");
-- Drives the progress counts (sent/failed/suppressed) and the "any PENDING or
-- QUEUED left?" check that flips a campaign to SENT.
CREATE INDEX "campaign_recipients_campaignId_status_idx"
    ON "campaign_recipients"("campaignId", "status");

ALTER TABLE "campaigns"
    ADD CONSTRAINT "campaigns_tenantId_fkey"
    FOREIGN KEY ("tenantId") REFERENCES "tenants"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "campaign_recipients"
    ADD CONSTRAINT "campaign_recipients_campaignId_fkey"
    FOREIGN KEY ("campaignId") REFERENCES "campaigns"("id")
    ON DELETE CASCADE ON UPDATE CASCADE;

-- Marketing consent for CUSTOMERS (US-016 column, populated by US-023's
-- unticked-by-default checkbox). Nullable with no backfill is the whole point:
-- NULL means no consent was ever given, so every existing customer starts
-- un-mailable for marketing and only an explicit opt-in changes that.
-- Transactional mail is unaffected. IF NOT EXISTS keeps this a no-op where the
-- column was already patched in by hand.
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "marketingConsentAt" TIMESTAMP(3);
